services:

  textbee-api:
    container_name: textbee-api

    build:
      context: ./api
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3001:3001"

    env_file:
      - ./api/.env

    environment:
      PORT: 3001
      REDIS_URL: redis://textbee-redis:6379

    depends_on:
      textbee-redis:
        condition: service_healthy

    networks:
      - textbee-network


  textbee-web:
    container_name: textbee-web

    build:
      context: ./web
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3000:3000"

    env_file:
      - ./web/.env

    environment:
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: https://sms.apis.isroot.in/api/v1

    depends_on:
      - textbee-api

    networks:
      - textbee-network


  textbee-redis:
    container_name: textbee-redis

    image: redis:alpine

    restart: always

    volumes:
      - redis_data:/data

    networks:
      - textbee-network

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  textbee-network:
    driver: bridge


volumes:
  redis_data: